server:
  port: ${PORT:8080}

spring:
  application:
    name: treasury-api
  
  r2dbc:
    url: r2dbc:postgresql://ep-shy-wind-agssb5wj-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslMode=require
    username: neondb_owner
    password: npg_QBbt1rDgGaO9
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
    properties:
      ssl: true
      sslMode: require

  datasource:
    url: jdbc:postgresql://ep-shy-wind-agssb5wj-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_QBbt1rDgGaO9
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    root: INFO
    com.rtcomops.treasury: DEBUG
    io.r2dbc.postgresql: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html