# Configurations communes à TOUS les environnements
server:
  port: ${PORT:8080}

spring:
  application:
    name: treasury-api
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    root: INFO
    com.rtcomops.treasury: DEBUG # Très détaillé pour votre code
    org.springframework.r2dbc: INFO # Moins verbeux pour r2dbc
    io.r2dbc.postgresql: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html