package com.rtcomops.treasury.application.mapper;

import com.rtcomops.treasury.application.dto.request.CreateBankTransactionRequest;
import com.rtcomops.treasury.application.dto.request.UpdateBankTransactionRequest;
import com.rtcomops.treasury.application.dto.response.BankTransactionResponse;
import com.rtcomops.treasury.domain.model.BankTransaction;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Mapper for converting between BankTransaction domain model and DTOs.
 *
 * @author RT-ComOps Team
 * @version 1.0.0
 * @since 2024-12-11
 */
@Component
public class BankTransactionMapper {

    private static final String DEFAULT_STATUS = "DRAFT";

    /**
     * Converts a CreateBankTransactionRequest to a BankTransaction domain model.
     * Note: The reference field is NOT set here - it will be generated by the service.
     *
     * @param request the create request DTO
     * @return a new BankTransaction domain model (without reference)
     */
    public BankTransaction toEntity(CreateBankTransactionRequest request) {
        LocalDateTime now = LocalDateTime.now();

        return BankTransaction.builder()
            .id(UUID.randomUUID())
            .bankAccountId(request.getBankAccountId())
            .transactionTypeId(request.getTransactionTypeId())
            // reference is generated automatically by the service
            .transactionDate(request.getTransactionDate())
            .valueDate(request.getValueDate() != null ? request.getValueDate() : request.getTransactionDate())
            .amount(request.getAmount())
            .direction(request.getDirection().toUpperCase())
            .description(request.getDescription())
            .partnerName(request.getPartnerName())
            .status(DEFAULT_STATUS)
            .systemDate(now)
            .isReconciled(false)
            .createdAt(now)
            .updatedAt(now)
            .build();
    }

    /**
     * Updates an existing BankTransaction domain model with values from UpdateBankTransactionRequest.
     * Note: reference is NEVER modifiable. transactionDate is only modifiable if status is DRAFT.
     *
     * @param existing the existing domain model
     * @param request the update request DTO
     * @return the updated BankTransaction domain model
     */
    public BankTransaction updateEntity(BankTransaction existing, UpdateBankTransactionRequest request) {
        if (request.getTransactionTypeId() != null) {
            existing.setTransactionTypeId(request.getTransactionTypeId());
        }
        // reference is never modifiable - skip even if provided
        // transactionDate is only modifiable if status is DRAFT
        if (request.getTransactionDate() != null && "DRAFT".equals(existing.getStatus())) {
            existing.setTransactionDate(request.getTransactionDate());
        }
        if (request.getValueDate() != null) {
            existing.setValueDate(request.getValueDate());
        }
        if (request.getAmount() != null) {
            existing.setAmount(request.getAmount());
        }
        if (request.getDirection() != null) {
            existing.setDirection(request.getDirection().toUpperCase());
        }
        if (request.getDescription() != null) {
            existing.setDescription(request.getDescription());
        }
        if (request.getPartnerName() != null) {
            existing.setPartnerName(request.getPartnerName());
        }
        if (request.getStatus() != null) {
            existing.setStatus(request.getStatus().toUpperCase());
        }
        existing.setUpdatedAt(LocalDateTime.now());

        return existing;
    }

    /**
     * Creates a copy of a BankTransaction domain model.
     *
     * @param original the original domain model
     * @return a copy of the domain model
     */
    public BankTransaction copy(BankTransaction original) {
        return BankTransaction.builder()
            .id(original.getId())
            .bankAccountId(original.getBankAccountId())
            .transactionTypeId(original.getTransactionTypeId())
            .reference(original.getReference())
            .transactionDate(original.getTransactionDate())
            .valueDate(original.getValueDate())
            .amount(original.getAmount())
            .direction(original.getDirection())
            .description(original.getDescription())
            .partnerName(original.getPartnerName())
            .status(original.getStatus())
            .systemDate(original.getSystemDate())
            .isReconciled(original.getIsReconciled())
            .reconciledAt(original.getReconciledAt())
            .statementLineId(original.getStatementLineId())
            .createdAt(original.getCreatedAt())
            .updatedAt(original.getUpdatedAt())
            .build();
    }

    /**
     * Converts a BankTransaction domain model to a BankTransactionResponse DTO.
     *
     * @param domain the domain model
     * @return the response DTO
     */
    public BankTransactionResponse toResponse(BankTransaction domain) {
        return BankTransactionResponse.builder()
            .id(domain.getId())
            .bankAccountId(domain.getBankAccountId())
            .transactionTypeId(domain.getTransactionTypeId())
            .reference(domain.getReference())
            .transactionDate(domain.getTransactionDate())
            .valueDate(domain.getValueDate())
            .amount(domain.getAmount())
            .direction(domain.getDirection())
            .description(domain.getDescription())
            .partnerName(domain.getPartnerName())
            .status(domain.getStatus())
            .systemDate(domain.getSystemDate())
            .isReconciled(domain.getIsReconciled())
            .reconciledAt(domain.getReconciledAt())
            .createdAt(domain.getCreatedAt())
            .updatedAt(domain.getUpdatedAt())
            .build();
    }

    /**
     * Converts a BankTransaction domain model to a BankTransactionResponse DTO with enriched details.
     *
     * @param domain the domain model
     * @param accountName the bank account name
     * @param typeCode the transaction type code
     * @param typeLabel the transaction type label
     * @return the response DTO with details
     */
    public BankTransactionResponse toResponseWithDetails(
            BankTransaction domain,
            String accountName,
            String typeCode,
            String typeLabel) {
        BankTransactionResponse response = toResponse(domain);
        response.setBankAccountName(accountName);
        response.setTransactionTypeCode(typeCode);
        response.setTransactionTypeLabel(typeLabel);
        return response;
    }
}
